# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86bf88fb10fdadd82ce497ab302a1c24f59a8fb834c0d3e39b4dc29c98cfc13cba638400359bec3569d069f3a4c3f20b6b7989be4eb1d668bda893b32e84f8cb

test:
  secret_key_base: 9d65dbf872dc2650cd9064c8a9cbb7b9d10eaea8363a4eace513f4c1a41197fc76c321c2096a680ca6bba843f95f1faa74a0a318b31b0ea712d51d8cbbe98daf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
